version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: phrm-postgres
    environment:
      POSTGRES_DB: phrm_db
      POSTGRES_USER: phrm_user
      POSTGRES_PASSWORD: phrm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
