// Re-export all UI components from a single file for cleaner imports
// This pattern allows importing multiple components in a single import statement
// Example: import { Button, Card, Input } from "@/components/ui"

export * from "./accordion"
export * from "./alert"
export * from "./avatar"
export * from "./badge"
export * from "./button"
export * from "./card"
export * from "./checkbox"
export * from "./dialog"
export * from "./dropdown-menu"
export * from "./form"
export * from "./input"
export * from "./label"
export * from "./loading"
export * from "./popover"
export * from "./progress"
export * from "./scroll-area"
export * from "./select"
export * from "./separator"
export * from "./switch"
export * from "./tabs"
export * from "./table"
export * from "./textarea"
export * from "./toast"
export * from "./use-toast"
export * from "./calendar"
